# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/py/vkvm_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(743, 415)
        self.connInfoBox = QtGui.QGroupBox(Dialog)
        self.connInfoBox.setGeometry(QtCore.QRect(490, 22, 241, 161))
        self.connInfoBox.setObjectName(_fromUtf8("connInfoBox"))
        self.ipLabel = QtGui.QLabel(self.connInfoBox)
        self.ipLabel.setGeometry(QtCore.QRect(13, 30, 111, 20))
        self.ipLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipLabel.setObjectName(_fromUtf8("ipLabel"))
        self.userEdit = QtGui.QLineEdit(self.connInfoBox)
        self.userEdit.setGeometry(QtCore.QRect(127, 58, 101, 20))
        self.userEdit.setReadOnly(False)
        self.userEdit.setObjectName(_fromUtf8("userEdit"))
        self.passwordEdit = QtGui.QLineEdit(self.connInfoBox)
        self.passwordEdit.setGeometry(QtCore.QRect(127, 88, 101, 20))
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setReadOnly(False)
        self.passwordEdit.setObjectName(_fromUtf8("passwordEdit"))
        self.idLabel = QtGui.QLabel(self.connInfoBox)
        self.idLabel.setGeometry(QtCore.QRect(28, 60, 101, 20))
        self.idLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.pwLabel = QtGui.QLabel(self.connInfoBox)
        self.pwLabel.setGeometry(QtCore.QRect(34, 90, 90, 20))
        self.pwLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwLabel.setObjectName(_fromUtf8("pwLabel"))
        self.serverEdit = QtGui.QLineEdit(self.connInfoBox)
        self.serverEdit.setGeometry(QtCore.QRect(127, 28, 101, 20))
        self.serverEdit.setReadOnly(False)
        self.serverEdit.setObjectName(_fromUtf8("serverEdit"))
        self.portEdit = QtGui.QLineEdit(self.connInfoBox)
        self.portEdit.setGeometry(QtCore.QRect(127, 118, 101, 20))
        self.portEdit.setReadOnly(False)
        self.portEdit.setObjectName(_fromUtf8("portEdit"))
        self.portLabel = QtGui.QLabel(self.connInfoBox)
        self.portLabel.setGeometry(QtCore.QRect(7, 120, 121, 16))
        self.portLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portLabel.setObjectName(_fromUtf8("portLabel"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 391))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 441, 341))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 441, 201))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.bladeBox = QtGui.QGroupBox(self.tab_2)
        self.bladeBox.setGeometry(QtCore.QRect(10, 220, 241, 141))
        self.bladeBox.setObjectName(_fromUtf8("bladeBox"))
        self.label_9 = QtGui.QLabel(self.bladeBox)
        self.label_9.setGeometry(QtCore.QRect(9, 81, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.bladeBox)
        self.label_8.setGeometry(QtCore.QRect(27, 50, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.bladeBox)
        self.label_7.setGeometry(QtCore.QRect(22, 20, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_10 = QtGui.QLabel(self.bladeBox)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.slotEdit = QtGui.QLineEdit(self.bladeBox)
        self.slotEdit.setGeometry(QtCore.QRect(100, 20, 131, 20))
        self.slotEdit.setReadOnly(True)
        self.slotEdit.setObjectName(_fromUtf8("slotEdit"))
        self.availEdit = QtGui.QLineEdit(self.bladeBox)
        self.availEdit.setGeometry(QtCore.QRect(100, 50, 131, 20))
        self.availEdit.setReadOnly(True)
        self.availEdit.setObjectName(_fromUtf8("availEdit"))
        self.overallEdit = QtGui.QLineEdit(self.bladeBox)
        self.overallEdit.setGeometry(QtCore.QRect(100, 80, 131, 20))
        self.overallEdit.setReadOnly(True)
        self.overallEdit.setObjectName(_fromUtf8("overallEdit"))
        self.discoveryEdit = QtGui.QLineEdit(self.bladeBox)
        self.discoveryEdit.setGeometry(QtCore.QRect(100, 110, 131, 20))
        self.discoveryEdit.setReadOnly(True)
        self.discoveryEdit.setObjectName(_fromUtf8("discoveryEdit"))
        self.statusBox = QtGui.QGroupBox(self.tab_2)
        self.statusBox.setGeometry(QtCore.QRect(260, 220, 191, 141))
        self.statusBox.setObjectName(_fromUtf8("statusBox"))
        self.statusList = QtGui.QListWidget(self.statusBox)
        self.statusList.setEnabled(True)
        self.statusList.setGeometry(QtCore.QRect(10, 20, 171, 111))
        self.statusList.setAutoScroll(False)
        self.statusList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.statusList.setObjectName(_fromUtf8("statusList"))
        item = QtGui.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.statusList.addItem(item)
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("orange.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.statusList.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.statusList.addItem(item)
        item = QtGui.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("grey.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.statusList.addItem(item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.addButton = QtGui.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(570, 200, 161, 23))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.removeButton = QtGui.QPushButton(Dialog)
        self.removeButton.setGeometry(QtCore.QRect(570, 230, 161, 23))
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.connButton = QtGui.QPushButton(Dialog)
        self.connButton.setGeometry(QtCore.QRect(570, 260, 161, 31))
        self.connButton.setObjectName(_fromUtf8("connButton"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.serverEdit)
        Dialog.setTabOrder(self.serverEdit, self.userEdit)
        Dialog.setTabOrder(self.userEdit, self.passwordEdit)
        Dialog.setTabOrder(self.passwordEdit, self.portEdit)
        Dialog.setTabOrder(self.portEdit, self.addButton)
        Dialog.setTabOrder(self.addButton, self.removeButton)
        Dialog.setTabOrder(self.removeButton, self.connButton)
        Dialog.setTabOrder(self.connButton, self.treeWidget)
        Dialog.setTabOrder(self.treeWidget, self.listWidget)
        Dialog.setTabOrder(self.listWidget, self.slotEdit)
        Dialog.setTabOrder(self.slotEdit, self.availEdit)
        Dialog.setTabOrder(self.availEdit, self.overallEdit)
        Dialog.setTabOrder(self.overallEdit, self.discoveryEdit)
        Dialog.setTabOrder(self.discoveryEdit, self.statusList)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Cisco UCS vKVM 접속 도우미 (Powered by HoonJo, JSKim)", None))
        self.connInfoBox.setTitle(_translate("Dialog", "접속 정보", None))
        self.ipLabel.setText(_translate("Dialog", "서버 매니저의 IP :", None))
        self.idLabel.setText(_translate("Dialog", "관리자 ID : ", None))
        self.pwLabel.setText(_translate("Dialog", "암      호 :", None))
        self.portEdit.setText(_translate("Dialog", "22", None))
        self.portLabel.setText(_translate("Dialog", "포트 번호 : ", None))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "등록된 랙 서버 매니저", None))
        self.bladeBox.setTitle(_translate("Dialog", "선택한 블레이드 서버 정보", None))
        self.label_9.setText(_translate("Dialog", "Overall Status : ", None))
        self.label_8.setText(_translate("Dialog", "Availability :", None))
        self.label_7.setText(_translate("Dialog", "Slot Status  : ", None))
        self.label_10.setText(_translate("Dialog", "Discovery : ", None))
        self.statusBox.setTitle(_translate("Dialog", "상태", None))
        __sortingEnabled = self.statusList.isSortingEnabled()
        self.statusList.setSortingEnabled(False)
        item = self.statusList.item(0)
        item.setText(_translate("Dialog", "접속 가능", None))
        item = self.statusList.item(1)
        item.setText(_translate("Dialog", "장착만 된 상태", None))
        item = self.statusList.item(2)
        item.setText(_translate("Dialog", "그 외의 상태", None))
        item = self.statusList.item(3)
        item.setText(_translate("Dialog", "상태 정보 조회 불가", None))
        self.statusList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "등록된 블레이드 서버 매니저", None))
        self.addButton.setText(_translate("Dialog", "추가/수정", None))
        self.removeButton.setText(_translate("Dialog", "삭제", None))
        self.connButton.setText(_translate("Dialog", "vKVM 접속", None))

